### POST Request
POST http://127.0.0.1:3000/api/v1/register
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@auth.com",
    "password": "P@ssw0rd",
    "full_name": "admin"
}

### POST Request
POST http://127.0.0.1:3000/api/v1/login
Content-Type: application/json

{
    "username": "admin",
    "password": "P@ssw0rd"
}

### GET Request
GET http://127.0.0.1:3000/api/v1/users
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM3MzkwNjM2LCJmdWxsX25hbWUiOiJBZG1pbiBVc2VyIiwicm9sZSI6ImFkbWluIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJhZG1pbiJ9.tj5mKgJYjxDDuiyha6rwiruT0Y1N13jdZfuWqghlaTg;

### GET Request
GET http://127.0.0.1:3000/api/v1/users/1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGF1dGguY29tIiwiZXhwIjoxNzM0MjY5MTA2LCJmdWxsX25hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoiYWRtaW4ifQ.PLWYfRLBqpHjD_n2u6Q7wRTtUV-hfynAjIxwQDfN9Vw;

### PUT Request
PUT http://127.0.0.1:3000/api/v1/users/1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGF1dGguY29tIiwiZXhwIjoxNzM0MjY5MTA2LCJmdWxsX25hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoiYWRtaW4ifQ.PLWYfRLBqpHjD_n2u6Q7wRTtUV-hfynAjIxwQDfN9Vw;

{
    "full_name": "super admin",
    "role": "admin"
}

### DELETE Request
DELETE  http://127.0.0.1:3000/api/v1/users/2
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGF1dGguY29tIiwiZXhwIjoxNzM0MjY5MTA2LCJmdWxsX25hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoiYWRtaW4ifQ.PLWYfRLBqpHjD_n2u6Q7wRTtUV-hfynAjIxwQDfN9Vw;
